<?php namespace Xefi\Faker\Container;
/**
 * @method array wordsAsArray(int $words = 3)
 * @method string words(int $words = 3)
 * @method array sentencesAsArray(int $sentences = 3)
 * @method string sentences(int $sentences = 3)
 * @method array paragraphsAsArray(int $paragraphs = 3)
 * @method string paragraphs(int $paragraphs = 3)
 * @method ?string getLocale()
 * @method int digit()
 * @method int number(int $min, int $max)
 * @method float float(float $min, float $max, int $decimals = 1)
 * @method mixed letter()
 * @method array|string shuffle(array|string $needle)
 * @method string shuffleString(string $needle)
 * @method array shuffleArray(array $needle)
 * @method string convertCharacters(string $string)
 * @method string semver()
 * @method string emoji()
 * @method string md5()
 * @method string sha1()
 * @method string sha256()
 * @method string sha512()
 * @method \DateTime dateTime(\DateTime|string|int $fromTimestamp = '-30 years', \DateTime|string|int $toTimestamp = 'now')
 * @method int timestamp(\DateTime|string|int $fromTimestamp = '-30 years', \DateTime|string|int $toTimestamp = 'now')
 * @method string sdl()
 * @method string tld()
 * @method string domain()
 * @method string ipv4()
 * @method string ipv6()
 * @method mixed macAddress()
 * @method mixed email()
 * @method string safeColorName()
 * @method string colorName()
 * @method string safeHexColor()
 * @method string hexColor()
 * @method array rgbColorAsArray()
 * @method string rgbColor()
 * @method string rgbCssColor()
 * @method array rgbaColorAsArray()
 * @method string rgbaColor()
 * @method string rgbaCssColor()
 * @method array hslColorAsArray()
 * @method string hslColor()
 * @method string hslCssColor()
 * @method array hslaColorAsArray()
 * @method string hslaColor()
 * @method string hslaCssColor()
 * @method string name(?string $gender = null)
 * @method string firstName(?string $gender = null)
 * @method string lastName()
 * @method mixed title(?string $gender = null)
 * @method string iban(?string $countryCode = null, ?string $format = null)
 * @method mixed boolean(int $percentage = 50)
 * @method mixed randomElement(array $array)
 * @method mixed randomKey(array $array)
 * @method \Intervention\Image\Image image(int $width = 300, int $height = 200, string $backgroundColor = '#cccccc', string $textColor = '#333333', ?string $text = null)
 * @method string imageUrl(int $width = 300, int $height = 200)
 */
	class Container{}